#!/usr/bin/env node
// build.js – assembles final HTML files from templates + shared JS sources.
//
// Usage:
//   node build.js
//
// Templates in /src/*.template.html are processed:
//   Lines matching  // @@include(path/to/file.js)
//   are replaced with the contents of the referenced file (relative to project root).
//
// Output files are written to the locations defined in OUTPUTS below.

import { readFileSync, writeFileSync, readdirSync } from "fs";
import { resolve, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

// Map: template path → output path (both relative to project root)
const OUTPUTS = [
  {
    template: "src/mobiKF8HuffConverter.template.html",
    output: "mobiKF8HuffConverter.html",
  },
  {
    template: "src/MobiReader-Huff-KF8.template.html",
    output: "Tools/MobiReader-Huff-KF8.html",
  },
  {
    template: "src/mobi7PalmDocConverter.template.html",
    output: "mobi7PalmDocConverter.html",
  },
  {
    template: "src/MobiReader-PalmDoc.template.html",
    output: "Tools/MobiReader-PalmDoc.html",
  },
  {
    template: "src/StarDictReaderValidator.template.html",
    output: "Tools/StarDictReaderValidator.html",
  },
];

const INCLUDE_RE = /^(\s*)\/\/\s*@@include\(([^)]+)\)\s*$/;

// Injected automatically after <body> in every compiled output.
const NOSCRIPT = `<noscript>
<style>body>*:not(noscript){display:none!important}</style>
<div style="font-family:'Segoe UI',sans-serif;max-width:480px;margin:80px auto;padding:28px;background:#fff3cd;border:1px solid #f59e0b;border-left:4px solid #f59e0b;border-radius:10px;color:#1c1e21;">
  <strong>⚠️ JavaScript is required</strong><br><br>
  This tool processes files locally in your browser using JavaScript. Please enable JS and reload.<br>
  <small style="color:#666">JavaScript jest wymagany do działania tej strony.</small>
</div>
</noscript>`;

function processTemplate(templatePath) {
  let src = readFileSync(resolve(__dirname, templatePath), "utf-8");

  // Strip any manually-placed <noscript>…</noscript> blocks so build is the sole source.
  src = src.replace(/<noscript>[\s\S]*?<\/noscript>\n?/g, "");

  const lines = src.split("\n");
  const result = [];

  for (const line of lines) {
    const m = line.match(INCLUDE_RE);
    if (m) {
      const [, indent, includePath] = m;
      const fullPath = resolve(__dirname, includePath.trim());
      const included = readFileSync(fullPath, "utf-8");
      // Indent every line of the included file to match the call-site indentation
      const indented = included
        .split("\n")
        .map((l) => (l.length ? indent + l : l))
        .join("\n");
      result.push(indented);
    } else {
      result.push(line);
    }
  }

  // Inject <noscript> right after <body>
  const html = result.join("\n").replace(/(<body[^>]*>)/, `$1\n${NOSCRIPT}`);

  const banner = [
    "<!--",
    "  !! THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY !!",
    `  Generated by build.js from ${templatePath}`,
    "  To make changes, edit the template and/or shared files from src/*.js,",
    "  then run:  node build.js",
    "-->",
  ].join("\n");

  return banner + "\n" + html;
}

let ok = true;
for (const { template, output } of OUTPUTS) {
  try {
    const html = processTemplate(template);
    const outPath = resolve(__dirname, output);
    writeFileSync(outPath, html, "utf-8");
    console.log(`✅  ${template}  →  ${output}`);
  } catch (err) {
    console.error(`❌  ${template}: ${err.message}`);
    ok = false;
  }
}

if (!ok) process.exit(1);
console.log("\nBuild complete.");

// ── Second pass: inject <noscript> into ALL html files in the project ─────────
// Covers compiled outputs, standalone tools, index.html — everything.
function injectNoscript(filePath) {
  let html = readFileSync(filePath, "utf-8");
  // Strip any existing noscript block first (idempotent)
  html = html.replace(/<noscript>[\s\S]*?<\/noscript>\n?/g, "");
  // Inject after <body ...>
  if (!html.includes("<body")) return; // skip non-body files
  html = html.replace(/(<body[^>]*>)/, `$1\n${NOSCRIPT}`);
  writeFileSync(filePath, html, "utf-8");
}

const HTML_DIRS = [__dirname, resolve(__dirname, "Tools")];
let injected = 0;
for (const dir of HTML_DIRS) {
  for (const file of readdirSync(dir)) {
    if (file.endsWith(".html")) {
      injectNoscript(resolve(dir, file));
      injected++;
    }
  }
}
console.log(`✅  Noscript injected into ${injected} HTML file(s).`);
