#!/usr/bin/env node
// build.js – assembles final HTML files from templates + shared JS sources.
//
// Usage:
//   node build.js
//
// Templates in /src/*.template.html are processed:
//   Lines matching  // @@include(path/to/file.js)
//   are replaced with the contents of the referenced file (relative to project root).
//
// Output files are written to the locations defined in OUTPUTS below.

import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

// Map: template path → output path (both relative to project root)
const OUTPUTS = [
    {
        template: 'src/mobiKF8HuffConverter.template.html',
        output:   'mobiKF8HuffConverter.html',
    },
    {
        template: 'src/MobiReader-Huff-KF8.template.html',
        output:   'Tools/MobiReader-Huff-KF8.html',
    },
    {
        template: 'src/mobi7PalmDocConverter.template.html',
        output:   'mobi7PalmDocConverter.html',
    },
    {
        template: 'src/MobiReader-PalmDoc.template.html',
        output:   'Tools/MobiReader-PalmDoc.html',
    },
];

const INCLUDE_RE = /^(\s*)\/\/\s*@@include\(([^)]+)\)\s*$/;

function processTemplate(templatePath) {
    const lines = readFileSync(resolve(__dirname, templatePath), 'utf-8').split('\n');
    const result = [];

    for (const line of lines) {
        const m = line.match(INCLUDE_RE);
        if (m) {
            const [, indent, includePath] = m;
            const fullPath = resolve(__dirname, includePath.trim());
            const included = readFileSync(fullPath, 'utf-8');
            // Indent every line of the included file to match the call-site indentation
            const indented = included
                .split('\n')
                .map(l => (l.length ? indent + l : l))
                .join('\n');
            result.push(indented);
        } else {
            result.push(line);
        }
    }

    const banner = [
        '<!--',
        '  !! THIS FILE IS AUTO-GENERATED. DO NOT EDIT DIRECTLY !!',
        `  Generated by build.js from ${templatePath}`,
        '  To make changes, edit the template and/or src/huffcdic-core.js,',
        '  then run:  node build.js',
        '-->',
    ].join('\n');

    return banner + '\n' + result.join('\n');
}

let ok = true;
for (const { template, output } of OUTPUTS) {
    try {
        const html = processTemplate(template);
        const outPath = resolve(__dirname, output);
        writeFileSync(outPath, html, 'utf-8');
        console.log(`✅  ${template}  →  ${output}`);
    } catch (err) {
        console.error(`❌  ${template}: ${err.message}`);
        ok = false;
    }
}

if (!ok) process.exit(1);
console.log('\nBuild complete.');

